title: hi.thesun
author: Trí Thông
email: hithesun@gmail.com
description: Để mặt trời soi rõ thân tâm này.

github_username: 
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: auto
# light-theme-accent-color: '#333'
# dark-theme-accent-color: '#eee'

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
